### ISSUE TITLE
 savedata.md 中 split_file.py 脚本使用问题

### ISSUE THREAD

**Issue by Intro1997** [Croden1999/Vita3K-quick-guide#3]
[这里](https://github.com/Croden1999/Vita3K-Quick-Guide/blob/master/psvita-to-vita3k/savedata.md?plain=1#L47) 说 “输入`python split_file.py sdslot`” 来使用脚本，但是脚本中没有地方读取 sdslot 这个参数，实际上使用 `python split_file.py` 这行代码就可以了

**Comment by Croden1999** [comment]
感谢提醒，确实可行，稍后提交新的更新

**Comment by Croden1999** [comment]
已在此修复[925071cc](https://github.com/Croden1999/Vita3K-Quick-Guide/commit/925071ccd0d709936a680e7c394cfb09959e1d15)
